export type RiskLevel = "critical" | "high" | "medium" | "low"
export type RoleType = "service" | "user" | "cross-account"
export type AccessLevel = "full" | "read" | "none" | "overprivileged"

export interface IAMRole {
  id: string
  account: string
  accountId: string
  roleName: string
  type: RoleType
  lastUsed: string
  usage30d: number // number of API calls in 30 days
  riskLevel: RiskLevel
  permissionsCount: number
  usedPermissionsCount: number
}

export interface LeastPrivilegeRecommendation {
  id: string
  roleName: string
  account: string
  currentPermissions: number
  usedPermissions: number
  unusedPermissions: string[]
  recommendation: string
  severity: RiskLevel
}

export interface CloudTrailEvent {
  id: string
  timestamp: string
  account: string
  role: string
  action: string
  resource: string
  sourceIp: string
  readWrite: "read" | "write"
  anomaly: boolean
  anomalyReason?: string
}

export interface AccessMatrixEntry {
  roleName: string
  account: string
  s3: AccessLevel
  rds: AccessLevel
  eks: AccessLevel
  lambda: AccessLevel
  ec2: AccessLevel
  secretsManager: AccessLevel
}

// ── IAM Roles ──────────────────────────────────────────────────

export const mockIAMRoles: IAMRole[] = [
  {
    id: "r1",
    account: "nexus",
    accountId: "967246349410",
    roleName: "keycloak-sre-developer-role",
    type: "user",
    lastUsed: "2026-04-09T14:23:00Z",
    usage30d: 1240,
    riskLevel: "medium",
    permissionsCount: 42,
    usedPermissionsCount: 28,
  },
  {
    id: "r2",
    account: "shared",
    accountId: "468411441302",
    roleName: "connectorder-s3-irsa",
    type: "service",
    lastUsed: "2026-04-10T08:15:00Z",
    usage30d: 8420,
    riskLevel: "low",
    permissionsCount: 6,
    usedPermissionsCount: 6,
  },
  {
    id: "r3",
    account: "nexus",
    accountId: "967246349410",
    roleName: "admin-full-access",
    type: "user",
    lastUsed: "2026-04-08T22:01:00Z",
    usage30d: 340,
    riskLevel: "critical",
    permissionsCount: 312,
    usedPermissionsCount: 23,
  },
  {
    id: "r4",
    account: "shared",
    accountId: "468411441302",
    roleName: "eks-node-role",
    type: "service",
    lastUsed: "2026-04-10T09:00:00Z",
    usage30d: 24000,
    riskLevel: "low",
    permissionsCount: 18,
    usedPermissionsCount: 18,
  },
  {
    id: "r5",
    account: "shared",
    accountId: "468411441302",
    roleName: "lambda-execution-role",
    type: "service",
    lastUsed: "2026-04-10T07:45:00Z",
    usage30d: 5600,
    riskLevel: "low",
    permissionsCount: 8,
    usedPermissionsCount: 7,
  },
  {
    id: "r6",
    account: "nexus",
    accountId: "967246349410",
    roleName: "cross-account-argocd",
    type: "cross-account",
    lastUsed: "2026-04-10T06:30:00Z",
    usage30d: 3200,
    riskLevel: "high",
    permissionsCount: 64,
    usedPermissionsCount: 31,
  },
  {
    id: "r7",
    account: "nowwaiting",
    accountId: "226282005159",
    roleName: "nw-api-gateway-role",
    type: "service",
    lastUsed: "2026-04-10T08:55:00Z",
    usage30d: 12400,
    riskLevel: "low",
    permissionsCount: 12,
    usedPermissionsCount: 11,
  },
  {
    id: "r8",
    account: "dodopoint",
    accountId: "852575311275",
    roleName: "dp-admin-legacy",
    type: "user",
    lastUsed: "2026-02-14T10:00:00Z",
    usage30d: 0,
    riskLevel: "critical",
    permissionsCount: 186,
    usedPermissionsCount: 0,
  },
  {
    id: "r9",
    account: "nexus",
    accountId: "967246349410",
    roleName: "signoz-collector-role",
    type: "service",
    lastUsed: "2026-04-10T09:10:00Z",
    usage30d: 18200,
    riskLevel: "low",
    permissionsCount: 14,
    usedPermissionsCount: 14,
  },
  {
    id: "r10",
    account: "shared",
    accountId: "468411441302",
    roleName: "rds-migration-role",
    type: "service",
    lastUsed: "2026-03-28T16:00:00Z",
    usage30d: 24,
    riskLevel: "medium",
    permissionsCount: 34,
    usedPermissionsCount: 12,
  },
  {
    id: "r11",
    account: "nexus",
    accountId: "967246349410",
    roleName: "github-actions-runner",
    type: "service",
    lastUsed: "2026-04-10T08:40:00Z",
    usage30d: 4800,
    riskLevel: "medium",
    permissionsCount: 48,
    usedPermissionsCount: 22,
  },
  {
    id: "r12",
    account: "nowwaiting",
    accountId: "226282005159",
    roleName: "nw-eso-secrets-role",
    type: "service",
    lastUsed: "2026-04-10T07:20:00Z",
    usage30d: 6800,
    riskLevel: "low",
    permissionsCount: 4,
    usedPermissionsCount: 4,
  },
  {
    id: "r13",
    account: "shared",
    accountId: "468411441302",
    roleName: "circleci-deploy-role",
    type: "service",
    lastUsed: "2026-04-09T18:30:00Z",
    usage30d: 920,
    riskLevel: "high",
    permissionsCount: 78,
    usedPermissionsCount: 19,
  },
  {
    id: "r14",
    account: "dodopoint",
    accountId: "852575311275",
    roleName: "dp-readonly-audit",
    type: "user",
    lastUsed: "2026-04-05T11:00:00Z",
    usage30d: 45,
    riskLevel: "low",
    permissionsCount: 8,
    usedPermissionsCount: 6,
  },
  {
    id: "r15",
    account: "nexus",
    accountId: "967246349410",
    roleName: "transit-gateway-role",
    type: "cross-account",
    lastUsed: "2026-04-10T05:00:00Z",
    usage30d: 2100,
    riskLevel: "high",
    permissionsCount: 52,
    usedPermissionsCount: 18,
  },
  {
    id: "r16",
    account: "nowwaiting",
    accountId: "226282005159",
    roleName: "nw-cloudfront-role",
    type: "service",
    lastUsed: "2026-04-10T09:05:00Z",
    usage30d: 3400,
    riskLevel: "low",
    permissionsCount: 10,
    usedPermissionsCount: 9,
  },
  {
    id: "r17",
    account: "shared",
    accountId: "468411441302",
    roleName: "terraform-state-role",
    type: "service",
    lastUsed: "2026-04-09T20:15:00Z",
    usage30d: 560,
    riskLevel: "medium",
    permissionsCount: 26,
    usedPermissionsCount: 14,
  },
  {
    id: "r18",
    account: "nexus",
    accountId: "967246349410",
    roleName: "keycloak-admin-sso",
    type: "user",
    lastUsed: "2026-04-07T13:45:00Z",
    usage30d: 180,
    riskLevel: "high",
    permissionsCount: 96,
    usedPermissionsCount: 24,
  },
]

// ── Least Privilege Recommendations ────────────────────────────

export const mockLeastPrivilegeRecommendations: LeastPrivilegeRecommendation[] = [
  {
    id: "lp1",
    roleName: "admin-full-access",
    account: "nexus",
    currentPermissions: 312,
    usedPermissions: 23,
    unusedPermissions: [
      "s3:*",
      "ec2:RunInstances",
      "ec2:TerminateInstances",
      "iam:CreateUser",
      "iam:DeleteUser",
      "iam:AttachRolePolicy",
      "rds:DeleteDBInstance",
      "lambda:DeleteFunction",
      "kms:ScheduleKeyDeletion",
      "organizations:*",
    ],
    recommendation:
      "Remove administrative wildcard permissions. Scope to specific S3 buckets used (aegis-config, nexus-artifacts). Replace ec2:* with ec2:Describe* only. Remove all IAM write permissions — use a separate break-glass role instead.",
    severity: "critical",
  },
  {
    id: "lp2",
    roleName: "cross-account-argocd",
    account: "nexus",
    currentPermissions: 64,
    usedPermissions: 31,
    unusedPermissions: [
      "ec2:DescribeInstances",
      "ec2:DescribeSecurityGroups",
      "s3:PutObject",
      "s3:DeleteObject",
      "iam:PassRole",
      "secretsmanager:GetSecretValue",
      "logs:CreateLogGroup",
    ],
    recommendation:
      "ArgoCD only needs EKS and ECR access for GitOps deployments. Remove S3 write, IAM:PassRole, and SecretsManager access. Use External Secrets Operator for secret injection instead.",
    severity: "high",
  },
  {
    id: "lp3",
    roleName: "dp-admin-legacy",
    account: "dodopoint",
    currentPermissions: 186,
    usedPermissions: 0,
    unusedPermissions: [
      "All 186 permissions unused",
      "s3:*",
      "ec2:*",
      "rds:*",
      "lambda:*",
      "iam:*",
      "dynamodb:*",
    ],
    recommendation:
      "This role has not been used in 55 days. The dodopoint account is disconnected. Recommend immediate deletion or quarantine of this role to eliminate dormant attack surface.",
    severity: "critical",
  },
  {
    id: "lp4",
    roleName: "circleci-deploy-role",
    account: "shared",
    currentPermissions: 78,
    usedPermissions: 19,
    unusedPermissions: [
      "ec2:*",
      "rds:ModifyDBInstance",
      "iam:CreateRole",
      "s3:DeleteBucket",
      "cloudformation:DeleteStack",
      "elasticloadbalancing:*",
    ],
    recommendation:
      "CI/CD role should only have ECR push, EKS deploy, and S3 artifact upload. Remove all EC2, RDS, IAM, and CloudFormation delete permissions. Add condition keys to restrict to specific CI runner IPs.",
    severity: "high",
  },
  {
    id: "lp5",
    roleName: "transit-gateway-role",
    account: "nexus",
    currentPermissions: 52,
    usedPermissions: 18,
    unusedPermissions: [
      "ec2:CreateVpc",
      "ec2:DeleteVpc",
      "ec2:CreateSubnet",
      "ec2:ModifyVpcPeeringConnectionOptions",
      "directconnect:*",
    ],
    recommendation:
      "Transit Gateway role has VPC creation permissions that should only exist in Terraform. Remove VPC lifecycle permissions and restrict to route table and attachment management only.",
    severity: "high",
  },
  {
    id: "lp6",
    roleName: "keycloak-admin-sso",
    account: "nexus",
    currentPermissions: 96,
    usedPermissions: 24,
    unusedPermissions: [
      "cognito-idp:*",
      "ses:SendEmail",
      "sns:Publish",
      "dynamodb:*",
      "lambda:InvokeFunction",
    ],
    recommendation:
      "Keycloak admin role has Cognito and DynamoDB permissions from a previous auth stack. Remove all Cognito, DynamoDB, and SES permissions. Keycloak uses RDS PostgreSQL and OIDC — no AWS auth services needed.",
    severity: "high",
  },
]

// ── CloudTrail Events ──────────────────────────────────────────

export const mockCloudTrailEvents: CloudTrailEvent[] = [
  {
    id: "ct1",
    timestamp: "2026-04-10T09:12:34Z",
    account: "nexus",
    role: "admin-full-access",
    action: "iam:CreateAccessKey",
    resource: "arn:aws:iam::967246349410:user/deploy-bot",
    sourceIp: "203.0.113.42",
    readWrite: "write",
    anomaly: true,
    anomalyReason: "Access key creation outside business hours from unknown IP",
  },
  {
    id: "ct2",
    timestamp: "2026-04-10T09:10:12Z",
    account: "shared",
    role: "eks-node-role",
    action: "ec2:DescribeInstances",
    resource: "arn:aws:ec2:ap-northeast-2:468411441302:instance/*",
    sourceIp: "10.0.1.45",
    readWrite: "read",
    anomaly: false,
  },
  {
    id: "ct3",
    timestamp: "2026-04-10T09:08:45Z",
    account: "nexus",
    role: "cross-account-argocd",
    action: "eks:DescribeCluster",
    resource: "arn:aws:eks:ap-northeast-2:967246349410:cluster/nexus-cluster",
    sourceIp: "10.0.2.10",
    readWrite: "read",
    anomaly: false,
  },
  {
    id: "ct4",
    timestamp: "2026-04-10T09:05:23Z",
    account: "nexus",
    role: "admin-full-access",
    action: "s3:PutBucketPolicy",
    resource: "arn:aws:s3:::nexus-artifacts",
    sourceIp: "203.0.113.42",
    readWrite: "write",
    anomaly: true,
    anomalyReason: "Bucket policy change by admin role — potential privilege escalation",
  },
  {
    id: "ct5",
    timestamp: "2026-04-10T09:02:11Z",
    account: "shared",
    role: "connectorder-s3-irsa",
    action: "s3:GetObject",
    resource: "arn:aws:s3:::connectorder-data/orders/2026-04-10.parquet",
    sourceIp: "10.0.3.22",
    readWrite: "read",
    anomaly: false,
  },
  {
    id: "ct6",
    timestamp: "2026-04-10T08:58:07Z",
    account: "nowwaiting",
    role: "nw-api-gateway-role",
    action: "execute-api:Invoke",
    resource: "arn:aws:execute-api:ap-northeast-2:226282005159:*/prod/GET/health",
    sourceIp: "10.0.4.15",
    readWrite: "read",
    anomaly: false,
  },
  {
    id: "ct7",
    timestamp: "2026-04-10T08:55:33Z",
    account: "nexus",
    role: "signoz-collector-role",
    action: "logs:PutLogEvents",
    resource: "arn:aws:logs:ap-northeast-2:967246349410:log-group:/signoz/traces",
    sourceIp: "10.0.1.30",
    readWrite: "write",
    anomaly: false,
  },
  {
    id: "ct8",
    timestamp: "2026-04-10T08:52:19Z",
    account: "shared",
    role: "circleci-deploy-role",
    action: "ecr:PutImage",
    resource: "arn:aws:ecr:ap-northeast-2:468411441302:repository/connectorder-api",
    sourceIp: "35.192.0.100",
    readWrite: "write",
    anomaly: false,
  },
  {
    id: "ct9",
    timestamp: "2026-04-10T08:48:44Z",
    account: "nexus",
    role: "github-actions-runner",
    action: "sts:AssumeRole",
    resource: "arn:aws:iam::468411441302:role/cross-account-deploy",
    sourceIp: "140.82.112.10",
    readWrite: "write",
    anomaly: false,
  },
  {
    id: "ct10",
    timestamp: "2026-04-10T08:45:02Z",
    account: "shared",
    role: "rds-migration-role",
    action: "rds:ModifyDBInstance",
    resource: "arn:aws:rds:ap-northeast-2:468411441302:db:shared-pg16",
    sourceIp: "10.0.2.55",
    readWrite: "write",
    anomaly: true,
    anomalyReason: "RDS modification outside maintenance window",
  },
  {
    id: "ct11",
    timestamp: "2026-04-10T08:40:15Z",
    account: "nowwaiting",
    role: "nw-eso-secrets-role",
    action: "secretsmanager:GetSecretValue",
    resource: "arn:aws:secretsmanager:ap-northeast-2:226282005159:secret:nw/db-credentials",
    sourceIp: "10.0.4.8",
    readWrite: "read",
    anomaly: false,
  },
  {
    id: "ct12",
    timestamp: "2026-04-10T08:35:28Z",
    account: "nexus",
    role: "keycloak-sre-developer-role",
    action: "s3:ListBucket",
    resource: "arn:aws:s3:::nexus-config",
    sourceIp: "10.0.1.12",
    readWrite: "read",
    anomaly: false,
  },
  {
    id: "ct13",
    timestamp: "2026-04-10T08:30:51Z",
    account: "dodopoint",
    role: "dp-admin-legacy",
    action: "sts:GetCallerIdentity",
    resource: "*",
    sourceIp: "198.51.100.77",
    readWrite: "read",
    anomaly: true,
    anomalyReason: "Disconnected account role probed from external IP — possible credential leak",
  },
  {
    id: "ct14",
    timestamp: "2026-04-10T08:25:09Z",
    account: "shared",
    role: "terraform-state-role",
    action: "s3:GetObject",
    resource: "arn:aws:s3:::terraform-state-shared/env/prod/terraform.tfstate",
    sourceIp: "10.0.2.60",
    readWrite: "read",
    anomaly: false,
  },
  {
    id: "ct15",
    timestamp: "2026-04-10T08:20:44Z",
    account: "nexus",
    role: "transit-gateway-role",
    action: "ec2:DescribeTransitGatewayAttachments",
    resource: "arn:aws:ec2:ap-northeast-2:967246349410:transit-gateway/*",
    sourceIp: "10.0.0.5",
    readWrite: "read",
    anomaly: false,
  },
  {
    id: "ct16",
    timestamp: "2026-04-10T08:15:22Z",
    account: "shared",
    role: "lambda-execution-role",
    action: "lambda:InvokeFunction",
    resource: "arn:aws:lambda:ap-northeast-2:468411441302:function:order-processor",
    sourceIp: "10.0.3.40",
    readWrite: "write",
    anomaly: false,
  },
  {
    id: "ct17",
    timestamp: "2026-04-10T08:10:08Z",
    account: "nexus",
    role: "keycloak-admin-sso",
    action: "secretsmanager:GetSecretValue",
    resource: "arn:aws:secretsmanager:ap-northeast-2:967246349410:secret:keycloak/admin-credentials",
    sourceIp: "10.0.1.20",
    readWrite: "read",
    anomaly: false,
  },
  {
    id: "ct18",
    timestamp: "2026-04-10T08:05:37Z",
    account: "nowwaiting",
    role: "nw-cloudfront-role",
    action: "cloudfront:GetDistribution",
    resource: "arn:aws:cloudfront::226282005159:distribution/E1234ABCDEF",
    sourceIp: "10.0.4.25",
    readWrite: "read",
    anomaly: false,
  },
  {
    id: "ct19",
    timestamp: "2026-04-10T08:00:19Z",
    account: "shared",
    role: "circleci-deploy-role",
    action: "ec2:RunInstances",
    resource: "arn:aws:ec2:ap-northeast-2:468411441302:instance/*",
    sourceIp: "35.192.0.100",
    readWrite: "write",
    anomaly: true,
    anomalyReason: "CI/CD role launching EC2 instances — unexpected for container-only deploys",
  },
  {
    id: "ct20",
    timestamp: "2026-04-10T07:55:42Z",
    account: "nexus",
    role: "github-actions-runner",
    action: "ecr:GetAuthorizationToken",
    resource: "*",
    sourceIp: "140.82.112.10",
    readWrite: "read",
    anomaly: false,
  },
  {
    id: "ct21",
    timestamp: "2026-04-10T07:50:11Z",
    account: "shared",
    role: "eks-node-role",
    action: "ecr:BatchGetImage",
    resource: "arn:aws:ecr:ap-northeast-2:468411441302:repository/connectorder-api",
    sourceIp: "10.0.1.45",
    readWrite: "read",
    anomaly: false,
  },
  {
    id: "ct22",
    timestamp: "2026-04-10T07:45:33Z",
    account: "nexus",
    role: "admin-full-access",
    action: "iam:AttachRolePolicy",
    resource: "arn:aws:iam::967246349410:role/new-service-role",
    sourceIp: "203.0.113.42",
    readWrite: "write",
    anomaly: true,
    anomalyReason: "Policy attachment by admin outside of Terraform — potential configuration drift",
  },
  {
    id: "ct23",
    timestamp: "2026-04-10T07:40:07Z",
    account: "nowwaiting",
    role: "nw-api-gateway-role",
    action: "dynamodb:Query",
    resource: "arn:aws:dynamodb:ap-northeast-2:226282005159:table/nw-sessions",
    sourceIp: "10.0.4.15",
    readWrite: "read",
    anomaly: false,
  },
  {
    id: "ct24",
    timestamp: "2026-04-10T07:35:55Z",
    account: "shared",
    role: "connectorder-s3-irsa",
    action: "s3:PutObject",
    resource: "arn:aws:s3:::connectorder-data/exports/daily-report.csv",
    sourceIp: "10.0.3.22",
    readWrite: "write",
    anomaly: false,
  },
  {
    id: "ct25",
    timestamp: "2026-04-10T07:30:28Z",
    account: "nexus",
    role: "signoz-collector-role",
    action: "xray:PutTraceSegments",
    resource: "*",
    sourceIp: "10.0.1.30",
    readWrite: "write",
    anomaly: false,
  },
]

// ── Access Matrix ──────────────────────────────────────────────

export const mockAccessMatrix: AccessMatrixEntry[] = [
  {
    roleName: "admin-full-access",
    account: "nexus",
    s3: "overprivileged",
    rds: "overprivileged",
    eks: "overprivileged",
    lambda: "overprivileged",
    ec2: "overprivileged",
    secretsManager: "overprivileged",
  },
  {
    roleName: "cross-account-argocd",
    account: "nexus",
    s3: "overprivileged",
    rds: "none",
    eks: "full",
    lambda: "none",
    ec2: "read",
    secretsManager: "overprivileged",
  },
  {
    roleName: "eks-node-role",
    account: "shared",
    s3: "read",
    rds: "none",
    eks: "full",
    lambda: "none",
    ec2: "read",
    secretsManager: "none",
  },
  {
    roleName: "connectorder-s3-irsa",
    account: "shared",
    s3: "full",
    rds: "none",
    eks: "none",
    lambda: "none",
    ec2: "none",
    secretsManager: "none",
  },
  {
    roleName: "lambda-execution-role",
    account: "shared",
    s3: "read",
    rds: "read",
    eks: "none",
    lambda: "full",
    ec2: "none",
    secretsManager: "read",
  },
  {
    roleName: "dp-admin-legacy",
    account: "dodopoint",
    s3: "overprivileged",
    rds: "overprivileged",
    eks: "overprivileged",
    lambda: "overprivileged",
    ec2: "overprivileged",
    secretsManager: "overprivileged",
  },
  {
    roleName: "circleci-deploy-role",
    account: "shared",
    s3: "full",
    rds: "overprivileged",
    eks: "full",
    lambda: "read",
    ec2: "overprivileged",
    secretsManager: "none",
  },
  {
    roleName: "keycloak-admin-sso",
    account: "nexus",
    s3: "read",
    rds: "full",
    eks: "none",
    lambda: "overprivileged",
    ec2: "none",
    secretsManager: "full",
  },
  {
    roleName: "transit-gateway-role",
    account: "nexus",
    s3: "none",
    rds: "none",
    eks: "none",
    lambda: "none",
    ec2: "overprivileged",
    secretsManager: "none",
  },
  {
    roleName: "github-actions-runner",
    account: "nexus",
    s3: "full",
    rds: "none",
    eks: "full",
    lambda: "read",
    ec2: "read",
    secretsManager: "read",
  },
]
